### PR TITLE
WiP+RF: store test outcomes in their own class

### PR DESCRIPTION
**Pull request by nno**
Work in Progress.
- Introduces separate classes for successes, failures, errors and skips.
- Adding XML output support could be added by changing @MOxUnitTestOutcome/getSummaryStr.m

### CODE REVIEW

**Comment by nno** [comment]
@scottclowe, would you be willing to take a look? i'm aware that some functions need more documentation; other than that, I would be curious to hear your thoughts about the refactoring.

**Comment by scottclowe** [comment]
We could introduce a generic `get` method. I am proposing to add one for `FunctionHandleTestCase` so that the attributes can be accessed from the methods of other classes in commit [1f3d9d664041ba4be1bc3834a41f94e9b7535e59](https://github.com/scottclowe/MOxUnit/commit/1f3d9d664041ba4be1bc3834a41f94e9b7535e59).

This would remove the need for the trivial `getDuration` and `getTest` methods, since they can be replaced with `get(obj, 'duration')` and `get(obj, 'test')`.

Also, having both an `isNonFailure` and `isSuccess` method seems like overkill to me. There is a lot of redundant information in the two things, and it seems more user-error-prone since one value be set incorrectly but not noticed because the other is correct. Maybe it would be better to use an error code system?
- -1=skip
- 0=success
- 1=fail
- 2=error

With this, we would have the error code as an attribute of the test outcome object too:
```
isSuccess = get(obj, 'errorCode')==0;
isFailure = get(obj, 'errorCode')>0;
isNonFailure = get(obj, 'errorCode')<=0;
```

In general I think the refactoring is very nice. It is much cleaner to have `MOxUnitTestReport` contain a single list of `TestOutcome` objects instead of maintaining four different lists of outcome cells by type.

**Comment by nno** [comment]
@scottclowe thanks for the comments. 

- While I see how using a generic `get` method could be used to get fields in the object, I prefer to keep individual `get_*` functions, because it makes explicit which information can be retrieved from the object. 

- NonFailure and Success are different for skipped tests. Also I don't like the numbering idea so much - I think the class type itself is a better approach to represent the outcome. For example, what if another type of testOutcome is added? 
Also, with get(obj, 'errorCode'), this would require setting an errorCode field in each object instance - which is the same all the time, so it is debatable whether this should be an instance field in the first place.

I've added some tests for the different Outcome classes, so that hopefully errors are avoided for the NonFailure and Success functions

**Comment by scottclowe** [comment]
Fair enough.

I've changed my mind about the error codes - I think you're right that as
these are values which should be class and not instance specific. And
unnecessarily restricting errors to use a one dimensional scalar value is
probably short sighted.

I favour using a single get method only because it is consistent with the
builtin matlab code for graphics and other objects which inherit from
handle. But it's your call on this.

Happy with the PR as-is.

**Comment by nno** [comment]
@scottclowe, very good. I'll leave out the get method for now and proceed with the merge.

**Pull request merged**
