### PR TITLE
Remove depreciated

### PR DESCRIPTION
**Pull request by jdbancal**
Removing some depreciated functions. To keep compatibility with not too old releases such as Octave 4.2, `isfolder` is still redirected to `isdir` in this case.

### CODE REVIEW

**Comment by jdbancal** [comment]
Is it possible that the are failing because `moxunit_set_path` was not called on the CI machine (hence the `MOxUnit/util` folder was not added to the path)?

**Comment by nno** [comment]
@jdbancal thanks for the PR, looks very good. I don't understand the output either, first:
```
Setup:  addpath("/home/MOxUnit/MOxUnit"); addpath("/home/MOdox/MOdox"); addpath("/home/MOcov/MOcov"); moxunit_set_path(); addpath('/github/workspace/MOxUnit');
```
which suggests that the path is set correctly; then
```
error: 'moxunit_util_isfolder' undefined near line 136 column 16
```

followed by what seems a contradictory result
```
suite: 31 tests
...............................
--------------------------------------------------

OK (passed=31)
Unit tests failed!
```

Also the number of tests seems too low. Will try and so some more digging.

**Comment by nno** [comment]
Since the code looks good to me I will go ahead and merge into master. Possibly there is a 'conflict' between two versions of MOxUnit (the one with the PR and the current one in master)...

**Comment by nno** [comment]
It seems the merge went well: https://github.com/MOxUnit/MOxUnit/runs/1435502750.

**Pull request merged**
