### PR TITLE
Add timing of unit tests

### PR DESCRIPTION
**Pull request by scottclowe**
- Each unit test is timed with `tic` and `toc`.
- The cumulative duration for the testsuite is tracked and added to
  the results object.

### CODE REVIEW

**Comment by scottclowe** [comment]
I would also like to save the duration of each test in the testresult object as `testresult.failures{i}{3}`, etc.

This would involve changing the structure of `testresult.success`, which currently is a cell array of MoxUnitTestCase objects and not a cell array of cells, unlike its cousin fields.

Would this be okay?

**Comment by nno** [comment]
Thanks for these changes. 

Yes, I think it would be good to change the representation of successes into cells to match the others (errors, failures, skips). Instead of storing it in the 3rd position, maybe the 2nd is better? That way all types of results have the test in the first, and the duration in the second position.

**Comment by scottclowe** [comment]
Done

**Comment by nno** [comment]
Looks good, thanks.

**Pull request merged**
